// Initialize analytics-node, per the analytics-node guide above.
const Analytics = require('analytics-node')
const analytics = new Analytics('pSnO74gzSxqTSg4Famn9KDJHdJPjpXRn')

// Import your auto-generated Typewriter client.
const typewriter = require('./src/analytics-autogenerated')

const violationConsoleLogger = (message, violations) => {
  console.log(message);
}

// Pass in your analytics-node instance to Typewriter.
typewriter.setTypewriterOptions({
  analytics: analytics,
  onViolation: violationConsoleLogger
})



typewriter.blogArticleViewed({
  properties: {
    category: 'test'
  },
  anonymousId: 'ano1234'
})
