const core = require('@actions/core')
const fs = require('fs')  
const axios = require('axios');

fs.readFile('protocols-diffs/src/analytics-autogenerated/plan.json', 'utf8', (err, jsonString) => {
  if (err) {
      console.log("File read failed:", err)
      return
  }
  try{
  const json = JSON.parse(jsonString)
  console.log(json)
  }
  catch(err){
  console.log('File data:', jsonString) 
  }
})
